---
- name: Uncordon node
  command: >-
    /usr/bin/kubectl uncordon
    {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false

- name: Wait for node to uncordon
  command: >-
    /usr/bin/kubectl get node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: wait_for_uncordon
  retries: 10
  delay: 10
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false
  until: not (wait_for_uncordon['stdout'] | from_json).spec.unschedulable is defined
